### ISSUE TITLE
Unable to generate same Proto AutoGenerated files.

### ISSUE THREAD

**Issue by asimashfaq** [bitloops/ddd-hexagonal-cqrs-es-eda#17]
I try to run the application with change in proto file. But when I generate the proto code. i generated completely different code.

**To Reproduce**
1.  Clone the repo.
2. yarn install
3. make change in todo.proto
4. Build the proto file.
5. Review generated code.

It should export the Protocode not just the interface.

**Screenshots**
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/8992522/230767232-20b16f0d-c93a-407e-9f36-4870d537ed8a.png">

**Comment by danias** [comment]
Hi @asimashfaq ! Can you try running `yarn proto` instead?

**Comment by danias** [comment]
Should be solved by #18 #15 and both yarn proto and ./protogen.sh should work now (if you have protoc-gen-ts installed as a global package in the second case and if you have protoc installed in both cases).

Please reopen this ticket if this is not the case.
