### ISSUE TITLE
Error 503 when adding a todo with empty title

### ISSUE THREAD

**Issue by sardounis** [bitloops/ddd-hexagonal-cqrs-es-eda#19]
**Describe the bug**
Internal Server Error occurs when a todo title is left empty, and add is pressed 
After that, all request - even valid todos get 503 from the server.

<img width="1191" alt="Screenshot 2023-04-10 at 11 37 04 AM" src="https://user-images.githubusercontent.com/1572341/230865711-4d9ae9a3-d4fd-45fb-80de-2bcb73c30fea.png">

**Comment by asimashfaq** [comment]
I think so error is comming from Nats 
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/8992522/231078860-6ad176f8-4c0a-4acc-b573-ed47e1784cc3.png">

**Note** I am not running inside the docker.

**Comment by danias** [comment]
Hi @asimashfaq, while both errors throw a 503, I think they are unrelated. The first error is thrown because probably something happens with protobuf and it converts the empty string to undefined and as a result title.value breaks because title is undefined. We are investigating this.

**Comment by danias** [comment]
Btw @asimashfaq the error you are getting is probably because you are not running the telemetry-consumer service which need to subscribe to events to avoid this error. Nonetheless, it should not cause you any issues even if you don't run it other than the error notifications.

**Comment by danias** [comment]
Issue has been resolved with the newest frontend release and issue could not be replicated using Postman and hitting the backend directly as it returns the expected error message:

<img width="831" alt="image" src="https://github.com/bitloops/ddd-hexagonal-cqrs-es-eda/assets/1571105/2a1291c1-d5c5-42a6-844d-a7fe2ec0e47a">
